# Generated by Django 4.2.1 on 2023-06-05 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeaListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', models.CharField(max_length=60)),
                ('origin', models.CharField(max_length=60)),
                ('tea_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=700)),
                ('color', models.CharField(max_length=20)),
                ('taste', models.CharField(max_length=100)),
                ('caffeine_level', models.CharField(max_length=50)),
                ('tea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_listing', to='teatimeapi.tealisting')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarTea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='teatimeapi.tealisting')),
            ],
        ),
    ]
