# Generated by Django 4.2.1 on 2023-06-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=500)),
                ('origin', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=700)),
                ('color', models.CharField(max_length=20)),
                ('taste', models.CharField(max_length=100)),
                ('caffeine', models.CharField(max_length=50)),
                ('tea_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_types', to='teatimeapi.teatype')),
            ],
        ),
    ]
